CREATE TABLE IF NOT EXISTS grocerylist (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
    active boolean NOT NULL,
    datecreated varchar NOT NULL,
    datemodified varchar NOT NULL,
    ownerid int REFERENCES appusers (id)
);