CREATE TABLE IF NOT EXISTS cmp_usersubscriptions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collectionid int REFERENCES collection (id),
    usermemberid int REFERENCES appusers (id),
    active boolean NOT NULL
);