CREATE TABLE IF NOT EXISTS cmp_recipeingredient (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity decimal NOT NULL,
    unit varchar NOT NULL,
    ingredientid int REFERENCES ingredient (id),
    recipeid int REFERENCES recipe (id)
);