CREATE TABLE IF NOT EXISTS ingredient (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
    description varchar,
    datecreated varchar NOT NULL,
    createdbyid int REFERENCES appusers (id)
);