CREATE TABLE IF NOT EXISTS appusers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname varchar NOT NULL,
    lastname varchar NOT NULL,
    handle varchar NOT NULL UNIQUE,
    email varchar NOT NULL UNIQUE,
    password varchar NOT NULL,
    active boolean NOT NULL,
    isadmin boolean NOT NULL,
    datecreated varchar NOT NULL,
    datemodified varchar NOT NULL
);