CREATE TABLE IF NOT EXISTS recipecomments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commentbody varchar NOT NULL,
    datecreated varchar NOT NULL,
    recipeid int REFERENCES recipe (id) NOT NULL,
    authorid int REFERENCES appusers (id) NOT NULL
);